### ISSUE TITLE
[BUG] get_ec2_instance_info.py fails on ca-west-1 region

### ISSUE THREAD

**Issue by cartalla** [aws-samples/hpc-cost-simulator#102]
**Describe the bug**

While updating the instance_type_info.json I got the following error:

```
Traceback (most recent call last):
  File "/workplace/cartalla/github/hpc-cost-simulator/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 523, in get_region_name
    region_name = data['partitions'][0]['regions'][region_code]['description']
KeyError: 'ca-west-1'
Traceback (most recent call last):
  File "./get_ec2_instance_info.py", line 28, in <module>
    ec2InstanceTypeInfo = EC2InstanceTypeInfo(args.region, json_filename=args.input, debug=args.debug)
  File "/workplace/cartalla/github/hpc-cost-simulator/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 126, in __init__
    region_name = self.get_region_name(region)
  File "/workplace/cartalla/github/hpc-cost-simulator/EC2InstanceTypeInfoPkg/EC2InstanceTypeInfo.py", line 523, in get_region_name
    region_name = data['partitions'][0]['regions'][region_code]['description']
KeyError: 'ca-west-1'
```

**To Reproduce**

```
./get_ec2_instance_info.py -i instance_type_info.latest.json -o instance_type_info.latest.csv
```

**Comment by cartalla** [comment]
Rather than raising the exception, should handle it and proceed with the valid regions and print out an error message with a summary of missing region names at the end.
