### ISSUE TITLE
[BUG] JobAnalyzer.py: invalid literal for int() with base 10: '1 day, 6'

### ISSUE THREAD

**Issue by cartalla** [aws-samples/hpc-cost-simulator#31]
## Describe the bug

When running JobAnalyzer.py on a jobs.csv I get many errors like the following.
I inserted a `raise` to stop on the first error for debug:

```
ERROR:2022-07-22 16:13:02,861: Exception reading /home/cartalla/onsemi/usca41-num-hosts.csv, line 3: invalid literal for int() with base 10: '1 day, 6'
fields:
203,1,0.0,1,2020-04-09T09:37:21,1969-12-31T16:00:00,2020-04-09T09:37:28,,0:00:00,2020-04-09T09:37:21,0:00:00,-18361--1 day, 6:22:39,0:00:00,0,-1,-1,-1,-1,-1,-1,-1,-1,,
ERROR:2022-07-22 16:13:02,861: Unhandled exception
Traceback (most recent call last):
  File "./JobAnalyzer.py", line 1278, in main
    jobAnalyzer.analyze_jobs()
  File "./JobAnalyzer.py", line 1143, in analyze_jobs
    job = self._scheduler_parser.parse_job()
  File "/workplace/cartalla/github/hpc-cost-simulator/CSVLogParser.py", line 61, in parse_job
    job = self._read_job_from_csv()
  File "/workplace/cartalla/github/hpc-cost-simulator/SchedulerLogParser.py", line 230, in _read_job_from_csv
    job = SchedulerJobInfo.from_dict(field_dict)
  File "/workplace/cartalla/github/hpc-cost-simulator/SchedulerJobInfo.py", line 252, in from_dict
    ru_utime = ru_utime,
  File "/workplace/cartalla/github/hpc-cost-simulator/SchedulerJobInfo.py", line 135, in __init__
    (self.wait_time, self.wait_time_td) = SchedulerJobInfo.fix_duration(wait_time)
  File "/workplace/cartalla/github/hpc-cost-simulator/SchedulerJobInfo.py", line 372, in fix_duration
    td = SchedulerJobInfo.str_to_timedelta(duration)
  File "/workplace/cartalla/github/hpc-cost-simulator/SchedulerJobInfo.py", line 496, in str_to_timedelta
    hours = int(values.pop())
ValueError: invalid literal for int() with base 10: '1 day, 6'
```

## To Reproduce.

Create a CSV file with the following line:

```
203,1,0.0,1,2020-04-09T09:37:21,1969-12-31T16:00:00,2020-04-09T09:37:28,,0:00:00,2020-04-09T09:37:21,0:00:00,-18361--1 day, 6:22:39,0:00:00,0,-1,-1,-1,-1,-1,-1,-1,-1,,
```

Run JobAnalyzer.py on it.

## Expected behavior 

I don't expect to get an error when parsing a job.csv that was generated by the parser.

## Repository Version

22d1e71

**Comment by cartalla** [comment]
The error is produced by the wait_time field which is a large negative number.
This is caused because the start_time was 0 and the wait_time was calculated as the difference between submit and start time.
I don't have the lsf record that caused this, so probably a problem in the LSF parser's output too. I'll try to reproduce that error with a testcase.
