### ISSUE TITLE
[BUG] json not defined in exception handler when run_time field invalid

### ISSUE THREAD

**Issue by cartalla** [aws-samples/hpc-cost-simulator#53]
**Describe the bug**

Customer got the following error while running JobAnalyzer.py

```
ERROR:2022-09-26 14:53:13,434: Unhandled exception
Traceback (most recent call last):
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/SchedulerLogParser.py", line 226, in _read_job_from_csv
    job = SchedulerJobInfo.from_dict(job_dict)
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/SchedulerJobInfo.py", line 249, in from_dict
    return SchedulerJobInfo(
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/SchedulerJobInfo.py", line 210, in __init__
    if not self.run_time:
AttributeError: 'SchedulerJobInfo' object has no attribute 'run_time'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/./JobAnalyzer.py", line 1380, in main
    jobAnalyzer.analyze_jobs()
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/./JobAnalyzer.py", line 1177, in analyze_jobs
    job = self._scheduler_parser.parse_job()
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/CSVLogParser.py", line 61, in parse_job
    job = self._read_job_from_csv()
  File "/Volumes/workplace/SA/cost_analysis/hpc-cost-simulator/SchedulerLogParser.py", line 228, in _read_job_from_csv
    logger.error(f"Exception reading {self._input_csv}, line {self._input_line_number}: {e}\njob_dict: {json.dumps(job_dict, indent=4)}")
NameError: name 'json' is not defined
```

**Repository Version**

59840dc

**Comment by cartalla** [comment]
The value of the field was:

`"-1 day, 23:59:21"`
